### ISSUE TITLE
Excluding does not work

### ISSUE THREAD

**Issue by Bartixxx32** [Stax124/Updater#2]
Hello, its a great script, but i have problem that -e (excluding) do not work at all, i still see data of excluded folder in hashtable.hash
I hope it can be fixed, and if i can give advice for better work, to make it exclude on updater generator and also downloader

My scenario, i have a project i want make updater but i have inside it folder of +- 30GB user data whih is created by program, and when i start the updater, it does hashing all files in this folder, it takes about 15 minutes to make not needed work, then if its possible to make exclude on updater and tell downloader to not hash this folder if it exist it would be great :)

**Comment by Bartixxx32** [comment]
For test purposes to share issue here i did it inside my pycharm env in this project
![image](https://user-images.githubusercontent.com/16412925/150653296-56d2299e-a260-40cb-8127-3fcefb40b7f3.png)
![image](https://user-images.githubusercontent.com/16412925/150653299-aecf3829-7f8d-4ed2-9eaa-0e188ed15968.png)

**Comment by Stax124** [comment]
Thanks for reporting this bug,
It should be now fixed in the main branch, please confirm that it works for you, so I can close this thread.

Thank you for using this small project, I never thought that someone else would use it.

**Comment by Bartixxx32** [comment]
Yeah, its working on hashtable creation, but seems it do not work in downloader part 

As i mentioned in first message, it would be really cool that i can exclude folders to check when updating process

like ```updater.exe -e cache -m localhost localhost/hashtable.hash -y```

becouse when used this command its still trying to hash 30gb+ of data :/

Haha dont look on what i used it, just wanted get some big folders really fast

![image](https://user-images.githubusercontent.com/16412925/150714823-9f3aa8a4-4c96-40c0-a461-f5c905020167.png)

**Comment by Bartixxx32** [comment]
Or if i can give idea, maybe make the updater downloader to check hashes of files only contained in hashtable.hash not all in current directory, it would make the script run blazing fast :D

**Comment by Stax124** [comment]
So, it should now check only files present in the remote hashtable, unless -a is passed as an argument.

**Comment by Bartixxx32** [comment]
![image](https://user-images.githubusercontent.com/16412925/151454928-ef2b65f1-a0ad-4f63-bf3f-711305b2aabe.png)
i have problem with function im gonna try debug it myself, but im unsure about it haha

Edit:
 after deleting this from line 40 hash_all it starts working, but as i can imagine not as inteeded due to -a will not work i guess

But i wonder why i often get mesage: File is corrupted, restart updater, i tried update and i got it 4 times and always for other file, but it passed, it would be cool to not force user to close script, but maybe add it in ```try:``` and if exception appear restart update process with hashing agin, it should work, but im not sure

**Comment by Bartixxx32** [comment]
Edit2: i think my "fix" didnt worked becouse seems if it cant find file from hashtable locally it crashes
![image](https://user-images.githubusercontent.com/16412925/151456521-ef864db3-2a54-49d5-ae33-43865c565879.png)

I for purpose deleted few files to check if it will be able to redownload them

I guess it check as you said only files what it found in hashtable, but has no exception if it wont? idk im not really understand how its working XD

**Comment by Stax124** [comment]
It should now throw an error to the console but continue with the process. The final output is then split with **---Changed or missing files---** line, if you need to process it afterwards. I'm also working on rewriting the documentation - it's a piece of crap right now.

**Comment by Bartixxx32** [comment]
Oh, thats a great news! Thanks a lot i see huge potential in this project!

**Comment by Bartixxx32** [comment]
i still face one issue, 
![image](https://user-images.githubusercontent.com/16412925/152058813-39cfead3-d214-447c-a48a-30ccda54603e.png)
and i cant understand why, but restarting works, i guess not bad idea is to do this thing in loop try becouse program is crashing :/

**Comment by Bartixxx32** [comment]
i still face one issue, 
![image](https://user-images.githubusercontent.com/16412925/152058813-39cfead3-d214-447c-a48a-30ccda54603e.png)
and i cant understand why, but restarting works, i guess not bad idea is to do this thing in loop try becouse program is crashing :/

**Comment by Bartixxx32** [comment]
i still face one issue, 
![image](https://user-images.githubusercontent.com/16412925/152058813-39cfead3-d214-447c-a48a-30ccda54603e.png)
and i cant understand why, but restarting works, i guess not bad idea is to do this thing in loop try becouse program is crashing :/

**Comment by Stax124** [comment]
This is expected behaviour and it's a countermeasure if your internet goes down or something bad happens. It stops the downloader from further overwriting files if one was downloaded, replaced and then hashed but hashes didn't match.

I can look more closely to it but this is probably on your side of things. I have a lot to do so I might not be able to check that today.
