### ISSUE TITLE
Ability to remove files that are not in hashtable

### ISSUE THREAD

**Issue by Bartixxx32** [Stax124/Updater#4]
Hello, i found a idea for this project, as somekind game modpack installer. Its working great, but i miss feature for deleting files
For example, delete all files, thats are not in hashtable, becouse sometimes update contains deletions too :)

**Comment by Stax124** [comment]
Working on it. Should arrive in 0.0.2

**Comment by Stax124** [comment]
Changes are pushed into the main branch

Clone the repo or pick up the artifact from [here](https://github.com/Stax124/Updater/actions/runs/2324344695) - should have precompiled executable

I still need to append these changes into the readme but expect a full release in about a week
